import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID,randomBytes} from 'node:crypto';
import {once} from 'node:events';
import pg from 'pg';
import {RemoteNodeStore} from '../src/remoteNodes/store.js';
import {RemoteWorkerActivationStore,REMOTE_RUNTIME_REVISION} from '../src/remoteNodes/workerActivationStore.js';
import {createRemoteNodeGateway} from '../src/remoteNodes/gateway.js';
import {createRemoteNodeClient} from '../src/remoteNodes/client.js';
import {assertIsolatedRemoteDatabase} from '../src/remoteNodes/isolation.js';
const url=process.env.REMOTE_NODE_TEST_DATABASE_URL;

test('collecting deployments require explicit activation and exact live instance; drain preserves current work',{skip:!url,timeout:30000},async t=>{
  const pool=new pg.Pool({connectionString:url,max:5});const guard=await pool.connect();const cleanup=[];
  t.after(async()=>{try{for(const action of cleanup.reverse())await action();}finally{guard.release();await pool.end();}});
  await assertIsolatedRemoteDatabase(pool);await guard.query('SELECT pg_advisory_lock(781137981)');
  for(const file of ['schema.sql','routeSchema.sql','workerConnectionSchema.sql','workerActivationSchema.sql'])await pool.query(await readFile(new URL(`../src/remoteNodes/${file}`,import.meta.url),'utf8'));
  const store=new RemoteNodeStore({pool});let centralReady=false;
  const activation=new RemoteWorkerActivationStore({store,verifyExecution:async()=>centralReady});
  const nodeId=randomUUID();const token=randomBytes(32).toString('hex');const slot='incremental-1';
  await store.registerNode({nodeId,token,capabilities:['fixture.activation']});
  await pool.query('INSERT INTO remote_ingestion.network_slots(node_id,slot,rota_worker_id) VALUES($1,$2,$3)',[nodeId,slot,`test-${nodeId}`]);
  const registration={nodeId,slot,deploymentId:randomUUID(),configHash:'a'.repeat(64)};
  await activation.register(registration);await activation.register(registration);
  await assert.rejects(activation.register({...registration,configHash:'b'.repeat(64)}),{code:'WORKER_DEPLOYMENT_CONFLICT'});
  const value={version:1,mode:'incremental_collect',node_id:nodeId,slot,deployment_id:registration.deploymentId,
    config_hash:registration.configHash,instance_id:randomUUID(),relay_boot_id:'b'.repeat(48),runtime_revision:REMOTE_RUNTIME_REVISION,accepting:true};
  const task=await store.enqueue({workKey:`activation-test:${nodeId}`,capability:'fixture.activation',input:{fixture:true},context:{}});
  const server=createRemoteNodeGateway({store,workerConnections:activation});server.listen(0,'127.0.0.1');await once(server,'listening');
  cleanup.push(async()=>{
    await new Promise(resolve=>{server.close(resolve);server.closeAllConnections();});
    await pool.query('DELETE FROM remote_ingestion.claims WHERE node_id=$1',[nodeId]);
    await pool.query('DELETE FROM remote_ingestion.tasks WHERE task_id=$1',[task]);
    await pool.query('DELETE FROM remote_ingestion.worker_connections WHERE node_id=$1',[nodeId]);
    await pool.query('DELETE FROM remote_ingestion.network_slots WHERE node_id=$1',[nodeId]);
    await pool.query('DELETE FROM remote_ingestion.nodes WHERE node_id=$1',[nodeId]);
  });
  const client=createRemoteNodeClient({url:`http://127.0.0.1:${server.address().port}`,token,allowLoopbackHttp:true});
  assert.equal((await client.workerHeartbeat(value)).ready_for_tasks,false);
  await assert.rejects(client.claim(randomUUID(),slot),{code:'INVALID_WORKER_CONNECTION'});
  assert.equal(await client.claim(randomUUID(),slot,value),null);
  assert.equal((await pool.query('SELECT generation FROM remote_ingestion.tasks WHERE task_id=$1',[task])).rows[0].generation,0);
  await assert.rejects(new RemoteWorkerActivationStore({store}).activate(value),{code:'CENTRAL_EXECUTION_NOT_CONFIGURED'});
  await assert.rejects(activation.activate(value),{code:'CENTRAL_EXECUTION_NOT_READY'});
  centralReady=true;await activation.activate(value);
  assert.equal((await client.workerHeartbeat(value)).ready_for_tasks,true);
  await assert.rejects(client.claim(randomUUID(),slot,{...value,instance_id:randomUUID()}),{code:'WORKER_CONNECTION_STALE'});
  const claimId=randomUUID();const lease=await client.claim(claimId,slot,value);assert.equal(lease.task_id,task);
  await activation.drain(nodeId,slot);
  assert.equal((await client.workerHeartbeat(value)).ready_for_tasks,false);
  assert.equal((await client.claim(claimId,slot,value)).task_id,task,'drain permits only exact existing claim replay');
  assert.equal(await client.claim(randomUUID(),slot,value),null);
  await client.heartbeat(lease);
  await pool.query("UPDATE remote_ingestion.worker_connections SET connected_until=now()-interval '1 second' WHERE node_id=$1",[nodeId]);
  const replacement={...value,instance_id:randomUUID(),relay_boot_id:'c'.repeat(48)};
  await assert.rejects(client.workerHeartbeat(replacement),{code:'WORKER_PREVIOUS_EXECUTION_UNSETTLED'});
  await pool.query("UPDATE remote_ingestion.tasks SET state='failed' WHERE task_id=$1",[task]);
  assert.equal((await client.workerHeartbeat(replacement)).ready_for_tasks,false);
  await assert.rejects(activation.activate(value),{code:'WORKER_NOT_READY'});
  await activation.activate(replacement);
  assert.equal((await client.workerHeartbeat({...replacement,accepting:false})).state,'draining');
  await assert.rejects(activation.activate(replacement),{code:'WORKER_NOT_READY'});
  await store.setNodeState(nodeId,'disabled');
  await assert.rejects(client.workerHeartbeat(replacement),{code:'UNAUTHORIZED'});
});
