import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { randomUUID, randomBytes } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import pg from 'pg';
import { RemoteNodeStore } from '../src/remoteNodes/store.js';
import { RemoteWorkerConnectionStore } from '../src/remoteNodes/workerConnectionStore.js';
import { createRemoteNodeGateway } from '../src/remoteNodes/gateway.js';
import { createRemoteNodeClient } from '../src/remoteNodes/client.js';
import { assertIsolatedRemoteDatabase } from '../src/remoteNodes/isolation.js';

const url = process.env.REMOTE_NODE_TEST_DATABASE_URL;
test('registered deployment ownership is verified without dispatching or mutating channel work', { skip: !url }, async t => {
  const pool = new pg.Pool({ connectionString: url, max: 4 });
  const cleanup = [];
  t.after(async () => { for (const action of cleanup.reverse()) await action(); await pool.end(); });
  await assertIsolatedRemoteDatabase(pool);
  const guard = await pool.connect();
  cleanup.push(() => guard.release());
  await guard.query('SELECT pg_advisory_lock(781137981)');
  for (const file of ['schema.sql', 'routeSchema.sql', 'workerConnectionSchema.sql']) await pool.query(await readFile(new URL(`../src/remoteNodes/${file}`, import.meta.url), 'utf8'));
  const store = new RemoteNodeStore({ pool }); const connections = new RemoteWorkerConnectionStore({ store });
  const nodeId = randomUUID(); const token = randomBytes(32).toString('hex'); const slot = 'incremental-1';
  await store.registerNode({ nodeId, token, capabilities: ['youtube.channel-plan.v1'] });
  await pool.query('INSERT INTO remote_ingestion.network_slots(node_id,slot,rota_worker_id) VALUES($1,$2,$3)', [nodeId, slot, `test-${nodeId}`]);
  cleanup.push(async () => {
    await pool.query('DELETE FROM remote_ingestion.worker_connections WHERE node_id=$1', [nodeId]);
    await pool.query('DELETE FROM remote_ingestion.network_slots WHERE node_id=$1', [nodeId]);
    await pool.query('DELETE FROM remote_ingestion.nodes WHERE node_id=$1', [nodeId]);
  });
  const registration = { nodeId, slot, deploymentId: randomUUID(), configHash: 'a'.repeat(64) };
  await connections.register(registration);
  await connections.register(registration);
  await assert.rejects(() => connections.register({ ...registration, deploymentId: randomUUID() }), { code: 'WORKER_DEPLOYMENT_CONFLICT' });
  const before = await pool.query('SELECT task_id,state,generation,node_id FROM remote_ingestion.tasks ORDER BY task_id');
  const gateway = createRemoteNodeGateway({ store, workerConnections: connections });
  gateway.listen(0,'127.0.0.1'); await once(gateway,'listening');
  cleanup.push(() => new Promise(resolve => { gateway.close(resolve); gateway.closeAllConnections(); }));
  const client = createRemoteNodeClient({ url: `http://127.0.0.1:${gateway.address().port}`, token, allowLoopbackHttp: true });
  const value = { version: 1, mode: 'connect_only', node_id: nodeId, slot, deployment_id: registration.deploymentId,
    config_hash: registration.configHash, instance_id: randomUUID(), relay_boot_id: 'b'.repeat(48) };
  const result = await client.workerHeartbeat(value);
  assert.equal(result.state, 'connected_waiting_activation'); assert.equal(result.ready_for_tasks, false);
  assert.equal((await client.workerHeartbeat(value)).instance_id, value.instance_id, 'ack loss can replay the same connection');
  await assert.rejects(() => client.workerHeartbeat({ ...value, instance_id: randomUUID() }), { code: 'WORKER_INSTANCE_BUSY' });
  await assert.rejects(() => client.workerHeartbeat({ ...value, config_hash: 'c'.repeat(64) }), { code: 'WORKER_DEPLOYMENT_MISMATCH' });
  await assert.rejects(() => client.workerHeartbeat({ ...value, node_id: randomUUID() }), { code: 'INVALID_WORKER_CONNECTION' });
  await assert.rejects(() => client.workerHeartbeat({ ...value, mode: 'active' }), { code: 'INVALID_WORKER_CONNECTION' });
  await pool.query("UPDATE remote_ingestion.worker_connections SET connected_until=clock_timestamp()-interval '1 second' WHERE node_id=$1", [nodeId]);
  const changed = { ...value, instance_id: randomUUID(), relay_boot_id: 'c'.repeat(48) };
  assert.equal((await client.workerHeartbeat(changed)).instance_id, changed.instance_id);
  await assert.rejects(() => client.workerHeartbeat(value), { code: 'WORKER_INSTANCE_BUSY' });
  await store.setNodeState(nodeId, 'draining');
  assert.equal((await client.workerHeartbeat(changed)).ready_for_tasks, false);
  await store.setNodeState(nodeId, 'disabled');
  await assert.rejects(() => client.workerHeartbeat(changed), { code: 'UNAUTHORIZED' });
  assert.deepEqual((await pool.query('SELECT task_id,state,generation,node_id FROM remote_ingestion.tasks ORDER BY task_id')).rows, before.rows);
});
