import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {once} from 'node:events';
import {randomUUID,randomBytes,generateKeyPairSync} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import pg from 'pg';
import {ProxyControlClient} from '../src/proxyControlClient.js';
import {createDeploymentCapacity} from '../src/remoteNodes/deploymentCapacity.js';
import {createRemoteDeploymentAdmin} from '../src/remoteNodes/deploymentAdmin.js';
import {RemoteNodeStore} from '../src/remoteNodes/store.js';
import {RemoteChannelPlanStore} from '../src/remoteNodes/channelPlanStore.js';
import {RemoteChannelRouteStore} from '../src/remoteNodes/channelRouteStore.js';
import {assertIsolatedRemoteDatabase} from '../src/remoteNodes/isolation.js';
const url=process.env.REMOTE_NODE_TEST_DATABASE_URL;

test('deployment grows network capacity from all saved nodes, retries the same target and preserves pause',{skip:!url},async t=>{
 const pool=new pg.Pool({connectionString:url,max:5});await assertIsolatedRemoteDatabase(pool);const guard=await pool.connect();await guard.query('SELECT pg_advisory_lock(781137981)');
 for(const f of ['schema.sql','routeSchema.sql','workerConnectionSchema.sql','workerActivationSchema.sql'])await pool.query(await readFile(new URL('../src/remoteNodes/'+f,import.meta.url),'utf8'));
 const nodeIds=[randomUUID(),randomUUID()],deploymentIds=[randomUUID(),randomUUID()];const requests=[];let fail=false,provisioned=61;
 const server=http.createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;assert.equal(req.url,'/capacity/ensure');assert.equal(req.headers.authorization,'Bearer fixture-control-token');const value=JSON.parse(body);requests.push(value.minimum_slots);res.setHeader('content-type','application/json');if(fail){res.statusCode=503;res.end(JSON.stringify({ok:false}));return;}provisioned=Math.max(provisioned,value.minimum_slots);res.end(JSON.stringify({ok:true,role:'channel',provisioned}));});server.listen(0,'127.0.0.1');await once(server,'listening');
 t.after(async()=>{await new Promise(r=>server.close(r));for(const table of ['node_deployments','worker_connections','network_slots','nodes'])await pool.query(`DELETE FROM remote_ingestion.${table} WHERE node_id=ANY($1::uuid[])`,[nodeIds]);guard.release();await pool.end();});
 const store=new RemoteNodeStore({pool}),routes=new RemoteChannelRouteStore({channelStore:new RemoteChannelPlanStore({store}),privateKey:generateKeyPairSync('ed25519').privateKey,secretKey:randomBytes(32),readRotaRoute:()=>assert.fail('no assignment during deployment'),assertBusinessFence:()=>{}});
 const capacity=createDeploymentCapacity({pool,localChannelSlots:61,client:new ProxyControlClient({controlUrl:`http://127.0.0.1:${server.address().port}`,token:'fixture-control-token',maxAttempts:1})});
 const image='registry.example/collect@sha256:'+'a'.repeat(64),gatewayUrl='https://center.example/remote';
 const admin=createRemoteDeploymentAdmin({store,routes,capacity,image,gatewayUrl,token:randomBytes(32).toString('hex'),execution:{allowsNode:()=>true,isProcessing:()=>false}});
 const plan=(index,count)=>({nodeId:nodeIds[index],deploymentId:deploymentIds[index],image,files:Object.fromEntries(Array.from({length:count},(_,i)=>{const slot=`incremental-${i+1}`;return [slot+'.json',JSON.stringify({version:1,mode:'incremental_collect',role:'incremental',node_id:nodeIds[index],deployment_id:deploymentIds[index],slot,gateway_url:gatewayUrl})+'\n'];}))});
 const initial=await admin.prepare(plan(0,3));assert.equal(provisioned,64);assert.deepEqual(await admin.prepare(plan(0,3)),initial);assert.equal(provisioned,64);
 fail=true;await assert.rejects(()=>admin.prepare(plan(0,5)),{code:'REMOTE_NETWORK_CAPACITY_UNAVAILABLE'});
 assert.equal((await pool.query('SELECT worker_count FROM remote_ingestion.node_deployments WHERE node_id=$1',[nodeIds[0]])).rows[0].worker_count,5);
 fail=false;const grown=await admin.prepare(plan(0,5));assert.equal(provisioned,66);assert.equal(grown.nodeToken,initial.nodeToken);assert.equal(grown.relayTokens['incremental-1'],initial.relayTokens['incremental-1']);
 await admin.prepare(plan(1,2));assert.equal(provisioned,68);await admin.prepare(plan(0,5));assert.equal(provisioned,68);
 assert.ok((await pool.query('SELECT activation_requested,enabled FROM remote_ingestion.worker_connections WHERE node_id=ANY($1::uuid[])',[nodeIds])).rows.every(w=>!w.activation_requested&&!w.enabled));
 await pool.query("UPDATE remote_ingestion.worker_connections SET connected_until=now()+interval '1 minute',accepting=true WHERE node_id=$1",[nodeIds[0]]);
 fail=true;await assert.rejects(()=>admin.setExecution({nodeId:nodeIds[0],deploymentId:deploymentIds[0],workerCount:5,enabled:true,expectedRequested:false}),{code:'REMOTE_NETWORK_CAPACITY_UNAVAILABLE'});
 assert.equal((await pool.query('SELECT bool_or(activation_requested) AS requested FROM remote_ingestion.worker_connections WHERE node_id=$1',[nodeIds[0]])).rows[0].requested,false);
 fail=false;await admin.setExecution({nodeId:nodeIds[0],deploymentId:deploymentIds[0],workerCount:5,enabled:true,expectedRequested:false});assert.equal(requests.at(-1),68);
 const before=requests.length;await admin.setExecution({nodeId:nodeIds[0],deploymentId:deploymentIds[0],workerCount:5,enabled:false,expectedRequested:true});assert.equal(requests.length,before,'pause does not require Rota capacity service');
});
