import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
import {randomUUID,randomBytes,generateKeyPairSync} from 'node:crypto';
import {setTimeout as delay} from 'node:timers/promises';
import pg from 'pg';
import {connectNats as connect} from '../src/remoteNodes/natsConnection.js';
import {RemoteNodeStore} from '../src/remoteNodes/store.js';
import {RemoteChannelPlanStore} from '../src/remoteNodes/channelPlanStore.js';
import {RemoteChannelRouteStore} from '../src/remoteNodes/channelRouteStore.js';
import {RemoteCenterExecutionSupervisor} from '../src/remoteNodes/centerExecutionSupervisor.js';
import {createTransportSignals} from '../src/remoteNodes/transportSignals.js';
import {createNatsProvisioning} from '../src/remoteNodes/natsProvisioning.js';
import {assertIsolatedRemoteDatabase} from '../src/remoteNodes/isolation.js';
const url=process.env.REMOTE_NODE_TEST_DATABASE_URL;
test('committed control notifications wake supervision and hot reload the real broker ACL',{skip:!url||!process.env.REMOTE_NATS_TEST_AUTH_FILE,timeout:30000},async t=>{
 const pool=new pg.Pool({connectionString:url,max:6});await assertIsolatedRemoteDatabase(pool);const guard=await pool.connect();await guard.query('SELECT pg_advisory_lock(781137981)');
 let signals,provisioning,supervisor;
 t.after(async()=>{await supervisor?.stop();await provisioning?.close();await signals?.close();guard.release();await pool.end();});
 for(const file of ['schema.sql','routeSchema.sql','workerConnectionSchema.sql','workerActivationSchema.sql','localIntakeSchema.sql','natsSchema.sql'])await pool.query(await readFile(new URL(`../src/remoteNodes/${file}`,import.meta.url),'utf8'));
 await pool.query('TRUNCATE remote_ingestion.nodes CASCADE');
 const store=new RemoteNodeStore({pool}),channelStore=new RemoteChannelPlanStore({store});
 signals=await createTransportSignals({connectionString:url});channelStore.transportSignals=signals;
 const routes=new RemoteChannelRouteStore({channelStore,privateKey:generateKeyPairSync('ed25519').privateKey,secretKey:randomBytes(32),readRotaRoute:async()=>{},assertBusinessFence:async()=>{}});
 const nodeId=process.env.REMOTE_NATS_TEST_NODE_ID,token=process.env.REMOTE_NATS_TEST_TOKEN;
 await store.registerNode({nodeId,token,capabilities:['test']});await routes.registerSlot(nodeId,'incremental-1','worker-test');
 await pool.query(`INSERT INTO remote_ingestion.worker_connections(node_id,slot,deployment_id,config_hash,role,mode,connected_until) VALUES($1,'incremental-1',$2,$3,'incremental','incremental_collect',clock_timestamp()+interval '30 seconds')`,[nodeId,randomUUID(),'a'.repeat(64)]);
 await delay(150); // Drain registration notifications before watching the next transaction.
 const changed=signals.watch('supervisor',{timeoutMs:2000});let woke=false;changed.wait.then(()=>woke=true);
 await pool.query("UPDATE remote_ingestion.worker_connections SET connected_until=clock_timestamp()+interval '40 seconds',last_seen_at=clock_timestamp() WHERE node_id=$1",[nodeId]);
 await delay(150);assert.equal(woke,false,'heartbeat-only update does not scan the fleet');
 const tx=await pool.connect();await tx.query('BEGIN');await tx.query('UPDATE remote_ingestion.worker_connections SET activation_requested=false WHERE node_id=$1',[nodeId]);await delay(100);assert.equal(woke,false);await tx.query('ROLLBACK');tx.release();
 await pool.query('UPDATE remote_ingestion.worker_connections SET activation_requested=false WHERE node_id=$1',[nodeId]);await changed.wait;assert.equal(woke,true);
 supervisor=new RemoteCenterExecutionSupervisor({store,channelStore,guardPool:pool,connection:{},prefix:'test',allowedNodeIds:[nodeId]});
 let ticks=0;supervisor.tick=async()=>{ticks++;};supervisor.start();await delay(1200);assert.equal(ticks,1,'idle supervisor no longer scans every second');
 await pool.query('UPDATE remote_ingestion.worker_connections SET activation_requested=true WHERE node_id=$1',[nodeId]);
 await delay(350);assert.equal(ticks,2,'committed start request wakes immediately');await supervisor.stop();
 const file=process.env.REMOTE_NATS_TEST_AUTH_FILE;
 await pool.query('INSERT INTO remote_ingestion.node_deployments(node_id,deployment_id,image,worker_count,credentials_cipher) VALUES($1,$2,$3,1,$4)',[nodeId,randomUUID(),'fixture',routes.encrypt({nodeToken:token},`node-deployment:${nodeId}`)]);
 provisioning=createNatsProvisioning({pool,routes,file,centerPassword:process.env.REMOTE_NATS_TEST_PASSWORD,localIntakePassword:process.env.REMOTE_NATS_TEST_LOCAL_PASSWORD,signals});await provisioning.sync();provisioning.start();
 assert.equal((await stat(file)).mode&0o777,0o600);
 const local=JSON.parse((await readFile(file,'utf8')).slice('users: '.length)).find(u=>u.user==='local-intake');
 assert.deepEqual(local.permissions,{publish:{deny:['>']},subscribe:['qy.local-intake.changed']});
 const second=randomUUID(),secondToken=randomBytes(32).toString('hex');await store.registerNode({nodeId:second,token:secondToken,capabilities:['test']});
 await pool.query('INSERT INTO remote_ingestion.node_deployments(node_id,deployment_id,image,worker_count,credentials_cipher) VALUES($1,$2,$3,1,$4)',[second,randomUUID(),'fixture',routes.encrypt({nodeToken:secondToken},`node-deployment:${second}`)]);
 const until=async read=>{const end=Date.now()+7000;while(!await read()){assert.ok(Date.now()<end);await delay(100);}};
 await until(async()=>(await readFile(file,'utf8')).includes(second));
 let connection;await until(async()=>{try{connection=await connect({servers:process.env.REMOTE_NATS_TEST_URL,user:second,pass:secondToken,tls:{caFile:process.env.REMOTE_NATS_TEST_CA},maxReconnectAttempts:0,timeout:500});return true;}catch{return false;}});
 await connection.flush();await store.setNodeState(second,'disabled');
 await until(async()=>!(await readFile(file,'utf8')).includes(second));
 await until(()=>connection.isClosed());
 // Restore the original fixture account for the following entry tests.
 await provisioning.sync();
});
